publishDir = "docs"
canonifyURLs = true
baseurl = "https://jbrandhorst.com"
DefaultContentLanguage = "en"
title = "Go Ahead"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsCodefences = true
pygmentsStyle= "friendly"
googleAnalytics = "UA-96154465-1"

[Params]
	subtitle = "Golang, gRPC and friends"
	logo = "img/icon.jpg"
	favicon = "img/favicon.ico"
	dateFormat = "January 2, 2006"
	commit = false
	rss = true
	comments = true
	readingTime = true

	[Params.staticman]
		api = "https://api.staticman.net/v2/entry/johanbrandhorst/blog/master/comments"
		pulls = "https://github.com/johanbrandhorst/blog/pulls"
		[Params.staticman.recaptcha]
			sitekey = "6LeZpToUAAAAAIVoByULm4eunmCL76Arn0dH-q8z"
			secret = "akUFoQUbDksw1BVWS162FgkLB65EwI85zeOQcPEmzXPULmhiE+d/LU/FKfnbeUjetjVeZmIDmEGNCKQc+8Er7rH1nAOJP6bN3oJvi/YtbSKEZfUdXAKvECyPfjl7J0rQ3YvtvEQX4VnyKqnAMottOaIZ3CXRI9TwbFFgYjSSJwQ="


[Author]
	name = "Johan Brandhorst"
	github = "johanbrandhorst"
	twitter = "JohanBrandhorst"
	linkedin = "johan-brandhorst-satzkorn-aa318220"
	website = "https://jbrandhorst.com"

[[menu.main]]
	name = "Blog"
	url = ""
	weight = 1

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 2

[[menu.main]]
	name = "Presentations"
	url = "page/presentations/"
	weight = 3

[[menu.main]]
	name = "Tags"
	url = "tags"
	weight = 4

