publishDir = "docs"
canonifyURLs = true
baseurl = "https://blog.mbrandhorst.com"
DefaultContentLanguage = "en"
title = "Shit I Shot"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsCodefences = true
pygmentsStyle= "friendly"
googleAnalytics = "UA-49575020-2"

[Params]
	subtitle = "A blog about cinematography"
	logo = "img/icon.jpg"
	favicon = "img/favicon.ico"
	dateFormat = "January 2, 2006"
	commit = false
	comments = true
	readingTime = true

	[Params.staticman]
		api = "https://api.staticman.net/v2/entry/maxbrand/blog/master/comments"
		pulls = "https://github.com/maxbrand/blog/pulls"
		[Params.staticman.recaptcha]
			sitekey = "6LeZpToUAAAAAIVoByULm4eunmCL76Arn0dH-q8z"
			secret = "akUFoQUbDksw1BVWS162FgkLB65EwI85zeOQcPEmzXPULmhiE+d/LU/FKfnbeUjetjVeZmIDmEGNCKQc+8Er7rH1nAOJP6bN3oJvi/YtbSKEZfUdXAKvECyPfjl7J0rQ3YvtvEQX4VnyKqnAMottOaIZ3CXRI9TwbFFgYjSSJwQ="


[Author]
	name = "Max Brandhorst-Satzkorn"
	instagram = "maxbrandop"
	email = "max.brandhorst@gmail.com"
	website = "https://mbrandhorst.com"

[[menu.main]]
	name = "Blog"
	url = ""
	weight = 1

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 2


